#!/usr/bin/perl -w
# $Id: makepp_build_cache_control,v 1.8 2009/02/09 22:07:39 pfeiffer Exp $

use  File::Basename;

my $makeppbuiltin = dirname($0).'/makeppbuiltin';
exec $makeppbuiltin, -MMpp::BuildCacheControl, @ARGV;
die "Failed to exec $makeppbuiltin: $!";
