CFLAGS := -O2 -pipe
LDFLAGS :=
TOOLSTARGET := arm-eabi

BINUTILSVER := 2.22
BINUTILSTAR := binutils-$(BINUTILSVER).tar.bz2
BINUTILSDIR := binutils-$(BINUTILSVER)

GCCVER := 4.7.1
GCCTAR := gcc-$(GCCVER).tar.bz2
GCCDIR := gcc-$(GCCVER)

GDBVER := 7.4
GDBTAR := gdb-$(GDBVER).tar.bz2
GDBDIR := gdb-$(GDBVER)

NEWLIBVER := 1.20.0
NEWLIBTAR := newlib-$(NEWLIBVER).tar.gz
NEWLIBDIR := newlib-$(NEWLIBVER)

PYTHONVER := 2.7.3
PYTHONTAR := Python-$(PYTHONVER).tar.bz2
PYTHONDIR := Python-$(PYTHONVER)

export PATH := $(TOOLSPREFIX)/bin:$(PATH)
